name: build for release
on:
  push:
    tags:
      - release*
  workflow_dispatch:
  
jobs:
  release:
    name: Release - ${{ matrix.platform.release_on }}
    strategy:
      matrix:
        platform:
          - release_on: ubuntu_x86
            os: ubuntu-20.04
            bin: precious

          - release_for: Windows_x86
            os: windows-latest
            bin: precious.exe

          - release_for: macOS_x86
            os: macOS-latest
            bin: precious

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: stable

      - name: build binary
        run: cargo build --release 
